//tag::vardef[]
:gh-repo-owner: jmini
:gh-repo-name: substring-finder
:project-name: SubstringFinder
:branch: master
:twitter-handle: j2r2b
:license: https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html
:license-name: Eclipse Public License - v 2.0

:git-repository: {gh-repo-owner}/{gh-repo-name}
:homepage: https://{gh-repo-owner}.github.io/{gh-repo-name}/
:issues: https://github.com/{git-repository}/issues
//end::vardef[]

//tag::header[]
= {project-name}
:author: Jeremie Bresson
:revnumber: 1.0.0

Java library for matching text ranges
//end::header[]

//tag::description[]
== Description

Java library for matching text ranges (defined by a start string and an end string) that can be included in each other.

Example, in following text, you want to match ranges that starts with `(` and ends with `)`:

----
5 + (4 + (1 + 2) / 3 - 5) * 10 / (3 + 2)
----

The first range is expected to be `(4 + (1 + 2) / 3 - 5)`.

This result `(4 + (1 + 2)` (matching the first opening bracket and the first closing bracket) is wrong.

This other result  `(4 + (1 + 2) / 3 - 5) * 10 / (3 + 2)` (matching the first opening bracket and the last closing bracket) is also wrong.

//end::description[]
Read more on the link:{homepage}[project home page].

//tag::contact-section[]
== Get in touch

Use the link:{issues}[issue tracker] on GitHub.

You can also contact me on Twitter: link:https://twitter.com/{twitter-handle}[@{twitter-handle}]
//end::contact-section[]

//tag::license-section[]
== License

Code is under link:{license}[{license-name}].
Documentation and slides are under the link:https://creativecommons.org/licenses/by-sa/4.0/[Creative Commons BY-SA 4.0]
//end::license-section[]
