:github-readme: ../README.adoc

include::{github-readme}[tags=vardef]

:projectpage: https://github.com/{gh-repo-owner}/{gh-repo-name}

include::{github-readme}[tags=header]

== URLs

* link:{homepage}[Project home] (this page)
* link:{projectpage}[GitHub project]
* link:{issues}[Issue tracker]

TIP: Do you want to improve this page? Please git-link:self[edit it on GitHub, edit].

include::{github-readme}[tags=description]

=== Text range example

In following text, you want to match ranges that starts with `(` and ends with `)`:

----
5 + (4 + (1 + 2) / 3 - 5) * 10 / (3 + 2)
----

The first range is expected to be `(4 + (1 + 2) / 3 - 5)`.

This result `(4 + (1 + 2)` (matching the first opening bracket and the first closing bracket) is wrong.

This other result  `(4 + (1 + 2) / 3 - 5) * 10 / (3 + 2)` (matching the first opening bracket and the last closing bracket) is also wrong.

Corresponding java code with `SubstringFinder`:

[source,java,indent=0]
----
include::../src/test/java/fr/jmini/utils/substringfinder/SubstringFinderTest.java[tags=example]
----

Where `SubstringFinder` corresponds to this imported class: `fr.jmini.utils.substringfinder.SubstringFinder`.

---

Other example:

Find the correct range defined `{` by `}` corresponding to the `main` method:

----
public static void main(String[] args) {
    if(args != null) {
        for (String s : args) {
            printArg(s);
        }
    }
}

public static void printArg(String arg) {
    System.out.println("Arg: " + arg);
}
----


=== String outside a range example

In following text, you want to find the comma `,` outside ranges defined by single quote `'`:

----
'Hello,world',5,true
----

The two correct matches are:

* Between `"` and `5`
* Between `5` and `t`

The first comma should be ignored because it is between `'` and `'`.

Corresponding java code with `PositionFinder`:

[source,java,indent=0]
----
include::../src/test/java/fr/jmini/utils/substringfinder/PositionFinderTest.java[tags=example]
----

Where `PositionFinder` corresponds to this imported class: `fr.jmini.utils.substringfinder.PositionFinder`.

---

Other example:

Find the world `video` that is not inside `<` and `>`:

----
This video: <video width="320" height="240" controls>
  <source src="movie.mp4" type="video/mp4">
</video>
----

== Download

Starting with version `1.0.1`, the library is hosted on maven central.

[source, xml, subs="verbatim,attributes"]
.Maven coordinates of the library
----
<dependency>
  <groupId>fr.jmini.utils</groupId>
  <artifactId>substring-finder</artifactId>
  <version>{last-stable-version}</version>
</dependency>
----

== Build

This project is using gradle.

Command to build the sources locally:

----
./gradlew build
----

Command to deploy to your local maven repository:

----
./gradlew publishToMavenLocal
----

Command to build the documentation page:

----
./gradlew asciidoctor
----

The output of this command is an HTML page located at `<git repo root>/build/docs/html5/index.html`.

=== For project maintainers

`signing.gnupg.keyName` and `signing.gnupg.passphrase` are expected to be set in your local `gradle.properties` file to be able to sign.
`sonatypeUser` and `sonatypePassword` are expected to be set in order to be able to publish to a distant repository.

Command to build and publish the result to maven central:

----
./gradlew publishToSonatype
----

Command to upload the documentation page on GitHub pages:

----
./gradlew gitPublishPush
----

Command to perform a release:

----
./gradlew release -Prelease.useAutomaticVersion=true
----

=== Using ssh-agent

Some tasks requires to push into the distant git repository (release task or updating the `gh-pages` branch).
If they are failing with errors like this:
----
org.eclipse.jgit.api.errors.TransportException: ... Permission denied (publickey).
---- 

Then `ssh-agent` can be used.
----
eval `ssh-agent -s`
ssh-add ~/.ssh/id_rsa
----
(link:https://superuser.com/a/990447/[source] for this approach)


include::{github-readme}[tags=contact-section]

include::{github-readme}[tags=license-section]
